"""Parrotts cluster TTS adapter — the only voice backend piratebot uses.

The cluster ``parrotts`` service holds the cloned-voice line library and
does all generation. piratebot just searches it, downloads resolved audio
files into a local cache on first hit, and hands the cached paths to the
avatar for lip-sync playback.

Public surface used by ``main.py``:

- ``tts.get_db()`` → ``ParrottsLineDB`` exposing
  ``get_random_from_category(...)`` and ``search_with_fallback(...)``
- ``tts.get_best_line(desired_text, category_hint, costume_type)``
- ``tts._get_audio_path(line)`` returns a local cached ``Path``
- ``tts.warmup()`` / ``tts.cleanup()``

Visemes are generated by the avatar running Rhubarb against the cached wav.
We could fetch them from parrotts via ``client.get_visemes(line_id)`` later
if local Rhubarb becomes a problem, but for now keeping it client-side
matches the existing avatar pipeline.
"""

from __future__ import annotations

import logging
import random
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from services.parrotts_vendor import ParrottsClient, ParrottsError

logger = logging.getLogger(__name__)


# Search match thresholds — same numbers we shipped on the legacy
# ChromaDB path so retrieval behavior stays consistent.
EXCELLENT_MATCH_THRESHOLD = 0.85
GOOD_MATCH_THRESHOLD = 0.65


@dataclass
class VoiceLine:
    """One pre-generated line. Mirrors what main.py + the avatar expect."""

    id: str
    text: str
    category: str = ""
    subcategory: str = ""
    tags: list[str] = field(default_factory=list)
    emotion: str = "neutral"


@dataclass
class SearchResult:
    line: VoiceLine
    similarity_score: float

    @property
    def is_good_match(self) -> bool:
        return self.similarity_score >= GOOD_MATCH_THRESHOLD

    @property
    def is_excellent_match(self) -> bool:
        return self.similarity_score >= EXCELLENT_MATCH_THRESHOLD


@dataclass
class VoiceLineSelection:
    """What main.py wraps a selected line in for downstream logging."""

    line: Optional[VoiceLine]
    text: str
    line_id: str
    method: str
    search_score: float = 0.0


def _line_from_parrotts(meta: dict) -> VoiceLine:
    """Convert a parrotts ``/v1/lines/{id}`` payload to a ``VoiceLine``."""
    return VoiceLine(
        id=meta["line_id"],
        text=meta["text"],
        category=meta.get("category") or "",
        subcategory=meta.get("subcategory") or "",
        tags=list(meta.get("tags") or []),
        emotion=meta.get("emotion") or "neutral",
        audio_file=None,
        viseme_file=None,
    )


class ParrottsLineDB:
    """Thin facade over the parrotts HTTP API for line lookup + search.

    Only implements the methods ``main.py`` actually calls; anything else
    is omitted so adding a new caller forces an explicit decision.
    """

    def __init__(self, client: ParrottsClient, character: str) -> None:
        self._client = client
        self._character = character

    # ----- read paths -----

    def get_line(self, line_id: str) -> Optional[VoiceLine]:
        meta = self._client.get_line(line_id)
        if meta is None:
            return None
        return _line_from_parrotts(meta)

    def get_random_from_category(
        self,
        category: str,
        subcategory: Optional[str] = None,
        exclude_recently_used: bool = True,  # parrotts handles cooldown server-side
    ) -> Optional[VoiceLine]:
        meta = self._client.random_line(
            character=self._character,
            category=category,
            subcategory=subcategory,
        )
        if meta is None:
            return None
        return _line_from_parrotts(meta)

    def search(
        self,
        query_text: str,
        n_results: int = 5,
        category: Optional[str] = None,
        subcategory: Optional[str] = None,
        tags: Optional[list[str]] = None,  # noqa: ARG002 — parrotts has no tag filter yet
        exclude_recently_used: bool = True,
        min_score: float = 0.0,
    ) -> list[SearchResult]:
        try:
            body = self._client.search_lines(
                q=query_text,
                character=self._character,
                category=category,
                subcategory=subcategory,
                top_k=n_results,
                exclude_recent=300.0 if exclude_recently_used else 0.0,
            )
        except ParrottsError as e:
            logger.warning("parrotts search failed: %s", e)
            return []

        results: list[SearchResult] = []
        for entry in body.get("results", []):
            similarity = float(entry.get("similarity", 0.0))
            if similarity < min_score:
                continue
            results.append(
                SearchResult(
                    line=_line_from_parrotts(entry["line"]),
                    similarity_score=similarity,
                )
            )
        return results

    def search_with_fallback(
        self,
        query_text: str,
        category_hint: Optional[str] = None,
        costume_type: Optional[str] = None,  # noqa: ARG002 — parrotts has no tag filter yet
    ) -> Optional[SearchResult]:
        """Same fallback ladder as ``VoiceLineDB.search_with_fallback``."""
        # Stage 1: specific category, excellent threshold
        if category_hint:
            results = self.search(
                query_text,
                n_results=3,
                category=category_hint,
                min_score=EXCELLENT_MATCH_THRESHOLD,
            )
            if results:
                return results[0]

        # Stage 2: specific category, good threshold
        if category_hint:
            results = self.search(
                query_text,
                n_results=3,
                category=category_hint,
                min_score=GOOD_MATCH_THRESHOLD,
            )
            if results:
                return results[0]

        # Stage 3: generic costume reactions
        results = self.search(
            query_text,
            n_results=5,
            category="costume_reactions",
            subcategory="generic",
        )
        if results:
            return random.choice(results[: min(3, len(results))])

        # Stage 4: positive fallbacks
        results = self.search(
            query_text,
            n_results=5,
            category="fallbacks",
            subcategory="positive",
        )
        if results:
            return random.choice(results[: min(3, len(results))])

        # Stage 5: any fallback
        results = self.search(query_text, n_results=5, category="fallbacks")
        if results:
            return random.choice(results)

        # Last resort: any random line for this character
        meta = self._client.random_line(character=self._character)
        if meta is not None:
            logger.warning("falling back to random line — no fallback category matched")
            return SearchResult(line=_line_from_parrotts(meta), similarity_score=0.0)

        logger.error("parrotts library is empty for character %s", self._character)
        return None

    # ----- write paths -----

    def mark_used(self, line_id: str) -> None:  # noqa: ARG002
        # parrotts auto-marks last_used_at on /v1/lines/{id}.wav GET, which
        # the avatar will trigger when it plays the cached file (... actually
        # the avatar plays from local disk, so the cluster never sees the GET.
        # We could explicitly POST a mark-used here later if cooldown drift
        # becomes a problem; for now this is a no-op.)
        pass

    def count(self) -> int:
        # Not used in main.py code paths; returning -1 makes it obvious if a
        # caller starts depending on it.
        return -1

    def get_categories(self) -> dict[str, int]:
        return {}


class ParrottsTTS:
    """piratebot's voice backend — talks to the cluster parrotts service."""

    def __init__(
        self,
        base_url: str,
        character: str,
        cache_dir: str | Path,
        request_timeout: float = 30.0,
    ) -> None:
        self.base_url = base_url
        self.character = character
        self.cache_dir = Path(cache_dir)
        self.cache_dir.mkdir(parents=True, exist_ok=True)
        self._client = ParrottsClient(base_url=base_url, timeout=request_timeout)
        self._db = ParrottsLineDB(self._client, character)
        self._last_selected: Optional[SearchResult] = None
        logger.info(
            "ParrottsTTS initialized: base_url=%s character=%s cache=%s",
            base_url,
            character,
            self.cache_dir,
        )

    # ----- accessors used by main.py -----

    def get_db(self) -> ParrottsLineDB:
        return self._db

    def get_best_line(
        self,
        desired_text: str,
        category_hint: Optional[str] = None,
        costume_type: Optional[str] = None,
    ) -> Optional[VoiceLine]:
        result = self._db.search_with_fallback(
            query_text=desired_text,
            category_hint=category_hint,
            costume_type=costume_type,
        )
        if result is None:
            return None
        self._last_selected = result
        return result.line

    def get_last_selected(self) -> Optional[SearchResult]:
        return self._last_selected

    def _get_audio_path(self, line: VoiceLine) -> Path:
        """Resolve a line to a local file path. Downloads on cache miss."""
        local = self.cache_dir / f"{line.id}.wav"
        if not local.exists():
            try:
                self._client.download_line(line.id, local)
            except ParrottsError as e:
                logger.error("parrotts download failed for %s: %s", line.id, e)
                raise
        return local

    # ----- lifecycle -----

    def warmup(self) -> None:
        """Probe the service so a misconfiguration fails fast at startup."""
        try:
            character = self._client.get_character(self.character)
        except ParrottsError as e:
            raise RuntimeError(
                f"parrotts unreachable at {self.base_url}: {e}"
            ) from e
        if character is None:
            raise RuntimeError(
                f"parrotts character {self.character!r} not registered. "
                f"Run tools/migrate_to_parrotts.py to seed it."
            )
        logger.info(
            "ParrottsTTS warmup: character %r ready (%s)",
            self.character,
            character.get("display_name", self.character),
        )

    def cleanup(self) -> None:
        self._client.close()

    def get_model_info(self) -> dict:
        return {
            "name": "ParrottsTTS",
            "type": "remote-cluster",
            "base_url": self.base_url,
            "character": self.character,
            "cache_dir": str(self.cache_dir),
        }
